---
title: "JunkSpace"
author: "BG"
date: "January 27, 2019"
output: 
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source( "utilz.R")
source( "consts.R")

loadLibraries()
set.seed(100)
```

# Project Plans

```{r pm}


var.Anon.Colz <-  c("Farmer/supplier name" , "Farmer branch")

var.Group.Byz <-  c( "Researcher name", "Farmer county/region")

var.Date.Colz <- c("Date of interview (dd/mm/yy)") 



```




# Data Exploration 

#Load DB 
```{r dbin, echo=FALSE}
df <- zLoadRawDataFrame( "agrics_raw.xlsx" )

df <- zAnonColumns( df, var.Anon.Colz )

df <- zFormatDateCol(df,  var.Date.Colz )

```

## Review Records

```{r samplestruct}
#kable( dfSummary( df ) )

pander( addmargins(table( df$`Researcher name`, df$`Farmer county/region`), margin = c(1,2) ) , caption = "Number of records by Researcher and Region")

zDescribeSampleStucture(df, var.Group.Byz)

dfSummary( df ) 
```


```{r missings}
# Fix Obvious  
df$`Researcher name`[which( df$`Researcher name` == "julie ouma")] <- "juliet ouma" 

## Date Values incorrect 
df[["ERR__Date_Field"]] <- ifelse( is.na( df$`Date of interview (dd/mm/yy)` ), 1, 0 )  

## Walkthrough issues 
zFlagIssues(df)


## missing values etc
pander(df %>% summarise_if( is.character, funs(nlevels(as.factor(.) ), nmiss=sum(is.na(.)))) , caption = "Qual Variables - Uniques and Missing Values")

```

## something fancy
```{r wordz}

var_colz = c("Where did you buy them?", "What were the inputs you purchased?", "Which alternative?", "Why did you select Agrics?", 
             "How did you pay for the Agrics package that you purchased in the last 12 months? - Other - Text", 
             "Please explain...32", "How has your quality of life improved?", "How has your quality of life worsened?", 
             "Please explain your score...39", "Please explain your score...40", "Please explain your score...41",
             "Please explain...43", "Regarding the interaction, would you say the respondent was:"
             )

map( var_colz, ~ zDirty.Wordcloud.it( df[.x] ) )

```